version: "3.9"
services:
  scgnn-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BASE_URL=http://scgnn-server:5001
    volumes:
      - ./logs:/app/logs
      - ./tmp:/tmp
  
  scgnn-server:
    container_name: scgnn-server
    image: frankfeng78/scgnn-server:0.1.8
    env_file:
      - .scgnn-server.env
    ports:
      - 5001:5001
    volumes:
      - ./logs:/app/logs
      - ./tmp:/tmp

networks:
  default:
    name: scgnn

  
